[versions]
gradle-starter = "0.53.0"
gradle-kotlinter = "3.12.0"
google-agp = "7.3.1"
maven-kotlin = "1.7.21"
google-androidx-annotation = "1.5.0"
google-material = "1.7.0"
google-recyclerview = "1.2.1"
google-fragment = "1.5.4"
maven-glide = "4.14.2"
maven-moshi = "1.14.0"

[libraries]
agp-gradle = { module = "com.android.tools.build:gradle", version.ref = "google-agp" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "maven-kotlin" }

androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "google-androidx-annotation" }
material-core = { module = "com.google.android.material:material", version.ref = "google-material" }
androidx-recyclerview-core = { module = "androidx.recyclerview:recyclerview", version.ref = "google-recyclerview" }
androidx-fragment-core = { module = "androidx.fragment:fragment", version.ref = "google-fragment" }
glide-core = { module = "com.github.bumptech.glide:glide", version.ref = "maven-glide" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "maven-glide" }
moshi-core = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "maven-moshi" }
moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "maven-moshi" }

[plugins]
jmailen-kotlinter = { id = "org.jmailen.kotlinter", version.ref = "gradle-kotlinter" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "maven-kotlin" }
starter-config = { id = "com.starter.config", version.ref = "gradle-starter" }
starter-versioning = { id = "com.starter.versioning", version.ref = "gradle-starter" }
starter-library-kotlin = { id = "com.starter.library.kotlin", version.ref = "gradle-starter" }
starter-library-android = { id = "com.starter.library.android", version.ref = "gradle-starter" }
